### ISSUE TITLE
 test .csv functionality

### ISSUE THREAD

**Issue by EstherPolak** [EdFarrell/MilkMachine#1]
Hi Ed, 

I did download the .csv file from the page by right mouse click it. 

The way it download made it not workable for importing in Milkmachine  I cannot attach te file, as github does not support csv so i do send it to you by email. Maybe you can either send me the csv by mail or explain how to correctly download it 
Thanks, Esther

**Comment by EdFarrell** [comment]
I didn't realize! I will get that fixed by trying a .txt instead.

**Comment by EdFarrell** [comment]
I just re-read that you right mouse clicked to download it. This is probably the reason for the strange formatting. Instead, clone MilkMachine to your local computer or download the zip file on the right hand side of the main page (https://github.com/EdFarrell/MilkMachine).

**Comment by EstherPolak** [comment]
I did download the ZIP and used the .csv, in sample data, and now it works totally fine!
