### ISSUE TITLE
time shift issue in test 8

### ISSUE THREAD

**Issue by EstherPolak** [EdFarrell/MilkMachine#2]
We did the test 8 again - speed up the 2nd minute of the file to 30 sec: 
• Change row 60-119 from 10:29:16/10:30:15 to 10:29:16/10:29:45
• Change rest of the file (row 120-end) 30 seconds backward to close the gap we created starting with 10:29:46

This works totally fine, we added a model, made a tour, exported it.

• Now the camera in the tour makes a strange move from 10:29:45 to 10:29:46.

We looked at the FlyTo in the kml and saw that the ‘duration of this particular FlyTo (10:29:44.9999) is 1.5e-05.

We changed that duration to 0.5 sec and then it works fine.

So all seems to work pretty well, except the FlyTo at the end of the TimeShift.

We sen both kml files. and the GGIS files all in one folder per email on nov 3

**Comment by EdFarrell** [comment]
This was a math bug. It was a division error where Python was abbreviating the decimal notation. I fixed this by overriding it and specifically asking for 6 decimal places. I just retested "Test 8" and it worked as expected. Please test and let me know how it goes.
