### ISSUE TITLE
Tracks in Europe Camera Failure

### ISSUE THREAD

**Issue by EstherPolak** [EdFarrell/MilkMachine#3]
We tried some test recordings in Amsterdam. The track did run in the MM plugin in QGIS perfectly.  The export to kml produced a file that projected the models in Amsterdam fine, but the camera movements where travelling all over the globe. 
We moved this track to the US, and then the exported tour with camera movements worked as expected. 
we suspect it having to do with being east of the 0 latitude line.

The attached file contains a folder with the shapefiles (GPSused) and both tours 
[edit.zip](https://github.com/EdFarrell/MilkMachine/files/568924/edit.zip)

**Comment by EdFarrell** [comment]
Please remind me what version of QGIS you are using, and what Mac version.

**Comment by EstherPolak** [comment]
I am using QGIS 2.4.0-Chugiak on OSX 10.9.5

**Comment by EstherPolak** [comment]
Hi Ed, I have the latest version of MM as well (nov 30 2015). I downloaded it just a few weeks ago.

MacOs is 10.10.5.

Best,

Ivar

**Comment by EstherPolak** [comment]
I ed, I see I accidentally closed this issue, and now opened it again. Sorry for this!
